### PR TITLE
Update Gradle

### PR DESCRIPTION
**Pull request by ShirleyNekoDev**
Upgrade Gradle 7.4 -> 8.0.2
see https://gradle.org/releases/ for changelogs

### CODE REVIEW

**Comment by ShirleyNekoDev** [comment]
Something something packages not found 🤔

**Comment by leMaik** [comment]
We could merge this, but the build needs to be fixed :man_shrugging:

**Comment by NotStirred** [comment]
Relevant issue https://github.com/openjfx/javafx-gradle-plugin/issues/140

**Comment by ShirleyNekoDev** [comment]
This should now be ready :tada:
Once we move on to Java 17 or newer (without breaking existing users' setups), we can also update the class file targetCompatability and sourceCompatibility, as well as the JavaFX library.

**Pull request merged**
