### PR TITLE
Add validation for y clipping ranges

### LINKED ISSUE #1444: Error when Map `Max Y level` is less than `Min Y level`
When the Map `Max Y level` is set less than the `Min Y level`, the following error occurs. Chunky remains fully functional.
```
Region Parser Error
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at se.llbit.chunky.world.biome.ArrayBiomePalette.get(ArrayBiomePalette.java:29)
	at se.llbit.chunky.map.BiomeLayer.<init>(BiomeLayer.java:41)
	at se.llbit.chunky.world.Chunk.loadSurface(Chunk.java:191)
	at se.llbit.chunky.world.Chunk.loadChunk(Chunk.java:172)
	at se.llbit.chunky.world.region.RegionParser.run(RegionParser.java:72)
```

### PR DESCRIPTION
**Pull request by leMaik**
Fixes #1444, which imho is mostly a GUI bug.

### CODE REVIEW

**Review by Peregrine05 — APPROVED** [review]

**Comment by NotStirred** [comment]
Would it be easier instead of having validation logic to instead do:
 - on set of `ymin` set `ymax` to `max(ymin, ymax)`
 - on set of `max` set `ymin` to `min(ymin, ymax)`

**Comment by leMaik** [comment]
@NotStirred i tried that and the ranges of the sliders changing all the time was very weird for me

**Comment by NotStirred** [comment]
imo it makes more sense to have sliders bounded by each other than having things highlighted red and the user must figure out why
just a suggestion of course :+1:

**Comment by jackjt8** [comment]
How difficult would it be to have an icon or message appear next to these fields if they are invalid?

If the fields get highlighted red and a warning icon shows up next to them which has a tooltip...?

**Comment by leMaik** [comment]
@NotStirred Tried it and while it's nice when using the sliders, it breaks text input (try entering a 20 for ymax after typing 10 into ymin).

@jackjt8 Like this?
image

**Pull request merged**
