### PR TITLE
Improve UI

### LINKED ISSUE #1173: Add a way to browse for a scene to load
Currently, Chunky allows you to change the world directory and browse for a world to load from within the _Change World_ menu. The _Load Scene_ menu does not have such functionality. The _Change Scene Directory_ option exists, but it is hidden in the rarely accessed _Options_ tab. _Change Scene Directory_ should be added to the _Load Scene_ menu, and "Browse for another scene" should be added as an option to that menu as well, to mirror the _Change World_ menu. It would also be useful in the event someone downloads a scene to render, but does not know that is should go in the `scenes` folder. Then they can simply browse for the scene.

### PR DESCRIPTION
**Pull request by leMaik**
Related to #1046 
Closes #1173 

Only the _Map View_ and _Options_ tabs are remaining.

image
image
image
image
image

### CODE REVIEW

**Comment by jackjt8** [comment]
I like these changes

**Comment by Peregrine05** [comment]
Maybe rename the `Help` tab to "Camera Controls" or simply move its contents into the `Camera` tab, so there are not two `Help` tabs/menus.

**Comment by jackjt8** [comment]
New UI looks really good and most things are self explanatory.

`Map View` right click menu item `Export chunks as zip file...` should read `Export selection as zip file...` given all other selection dependant options use this terminology.
image


`Scene` > `Open scene directory` should be greyed out if no scene is loaded.

image


`File` > `Save`, `Save as..`, `Save  copy...` work as expected.

`File` Shortcuts are... going to have a learning curve. If you don't click on the left pane you end up moving your render... 

image

> I do believe the restoring the `Lock` button that was around from the 1.X days is worthwhile. That way people have disable keyboard/mouse inputs to the preview to avoid accidental movement.

`Resources Packs & Textures`

I wonder if we need a pop out editor if we have such a small tab? Surely we could embed the list of resource packs to make it quicker and easier to see what packs are loaded?

image

We should also improve how information is displayed here. Showing the full path to the resource pack is not user-friendly / shouldn't be the main focus. We should display the file/folder name, resource pack version (pack.mcmeta), and pack description (pack.mcmeta) as a priority in my opinion. I may create a separate issue to track these changes as they may be out of scope for this PR and would delay things.

---

In any case this is a massive improvement.

**Comment by leMaik** [comment]
@jackjt8 Thanks for the feedback! :+1: 

I improved the chunk export label. The _open scene directory_ button is now disabled if the scene directory doesn't exist. The shortcuts do nothing if the render view is focused, so I guess that's fine for now.

As discussed in chat, the resource packs dialog is out-of-scope for this PR, but @ShirleyNekoDev has some great work going on, so it might be vastly improved in the future.

**Pull request merged**
