### PR TITLE
Fix `NoSuchMethodError` in `AnimatedQuadModel`

### LINKED ISSUE #1187: Parallel projection in the latest snapshot causes an error
Java 8 update 321
Chunky 2.5.0-SNAPSHOT.70.g3d819751

Using parallel projection gives this error:
```
Render worker 0 crashed with uncaught exception.
java.lang.NoSuchMethodError: java.lang.Math.floorMod(JI)I
    at se.llbit.chunky.model.AnimatedQuadModel.intersect(AnimatedQuadModel.java:52)
    at se.llbit.chunky.block.AbstractModelBlock.intersect(AbstractModelBlock.java:28)
    at se.llbit.math.Octree.enterBlock(Octree.java:537)
    at se.llbit.chunky.renderer.scene.Scene.worldIntersection(Scene.java:792)
    at se.llbit.chunky.renderer.scene.Scene.intersect(Scene.java:768)
    at se.llbit.chunky.renderer.scene.PreviewRayTracer.nextIntersection(PreviewRayTracer.java:98)
    at se.llbit.chunky.renderer.scene.PreviewRayTracer.trace(PreviewRayTracer.java:44)
    at se.llbit.chunky.renderer.scene.Scene.rayTrace(Scene.java:735)
    at se.llbit.chunky.renderer.PreviewRenderer.lambda$render$0(PreviewRenderer.java:99)
    at se.llbit.chunky.renderer.TileBasedRenderer.lambda$submitTiles$1(TileBasedRenderer.java:82)
    at se.llbit.chunky.renderer.RenderWorkerPool.work(RenderWorkerPool.java:141)
    at se.llbit.chunky.renderer.RenderWorkerPool.access$100(RenderWorkerPool.java:29)
    at se.llbit.chunky.renderer.RenderWorkerPool$RenderWorker.run(RenderWorkerPool.java:101)
```

### PR DESCRIPTION
**Pull request by ThatRedox**
* Set Java build release version to Java 8
* Replace `Math.floorMod` with simple cast to `int`
* Fix potential Java 8 compatibility issue in `CrcOutputStream`

This closes #1187

### CODE REVIEW

**Comment by NotStirred** [comment]
`floorMod` -> cast to int is different behaviour, just making sure this intentional

**Comment by NotStirred** [comment]
`floorMod` -> cast to int is different behaviour, just making sure this intentional

**Comment by NotStirred** [comment]
wait... it was doing modulo with max int..?! ok ignore me

**Comment by ThatRedox** [comment]
I think it might still be different, but I couldn't see why it used the modulo instead of a cast in the first place and it should have the same effect (unless that matches Minecraft's method in which case it just needs to cast `Integer.MAX_VALUE` to a long).

**Pull request merged**
