### PR TITLE
Use the JavaFX gradle plugin when building with Java 10 or later.

### LINKED ISSUE #787: Building version 2 throws errors
I have latest JRE and JDK installed but gradlew.bat throws tons of errors. 

I've put all the errors in file 

[log.txt](https://github.com/chunky-dev/chunky/files/5836087/log.txt)

Probably I'm just dumb and can't get it to work

### PR DESCRIPTION
**Pull request by leMaik**
Based on @aTom3333's snapshot. This doesn't break the build with Java 8 but can someone verify that it works as intended with Java 10+?

Fixes #787

### CODE REVIEW

**Comment by jackjt8** [comment]
```
A problem occurred evaluating root project 'chunky'.
> Could not find method plugins() for arguments [build_ykf11fq8wmnzmwxcbr4mpi0h$_run_closure1@40110d00] on root project 'chunky' of type org.gradle.api.Project.
```

aTom3333's patch file works fine for me.

**Comment by leMaik** [comment]
@jackjt8 Changed it, please try again

**Comment by jackjt8** [comment]
The changed version works... But for some reason the Actions script doesn't like it.

**Comment by leMaik** [comment]
@jackjt8 It didn't work for Java 8 anymore… Loading plugins conditionally just doesn't seem to work.

**Pull request closed without merging**
