### PR TITLE
Add viewport lines to camera preset icons

### PR DESCRIPTION
**Pull request by NotStirred**
as requested in https://github.com/chunky-dev/chunky/pull/1363#issuecomment-1183506713

### CODE REVIEW

**Comment by NotStirred** [comment]
image

**Review by Peregrine05 — APPROVED** [review]
This looks good. The only "problem" that I still see is that the "chunk" is viewed diagonally, which does not really make sense if the camera is aiming toward a diagonal direction (i.e., North-West), but I doubt that many people will care.

**Comment by Peregrine05** [comment]
Well, considering that the projection is parallel, there will be no perspective in the preview, so that is approximately how it will look.

**Comment by NotStirred** [comment]
Sadly we have to pick between a descriptive image, and subtly incorrect lines
or less helpful image with correct lines

**Comment by Peregrine05** [comment]
I would choose the more helpful but "incorrect perspective" image. Overall, it makes more sense.

**Review by leMaik — APPROVED** [review]

**Pull request merged**
