### PR TITLE
Sliders to zero

### LINKED ISSUE #733: Sliders to 0
Any setting sliders will not allow you to go to zero, but the textbox does allow it to.

### PR DESCRIPTION
**Pull request by blueplanet150**
Fixes #733 

The issue says that there are setting sliders, which dont go down to zero, but the textbox allows it. 
I noticed there are 2 casses where this happens:
1. When DoubleAdjuster.setRange(min, max, slider_min) is called to set the range. I suppose this is for the logarithmic scaling, slider_min preventing values too close to zero. I fixed this problem, but it was only in one case (fog density). Now, setRange(min, max) will automatically set the minimum for logarithmic scaling (logScaleStart) to  0.01. For slider positions < logScaleStart, the value is set to 0. Also, for values < logScaleStart, the slider position is set to zero.
2. When DoubleAdjuster(setRange(min, max) is called to set the range, with min > 0. In this case,the slider will go down to min, but the textbox can still be set to ANY value, including zero. I did not fix this. Its a different Problem.

### CODE REVIEW

**Comment by leMaik** [comment]
Nice first PR! :partying_face: 

So can the slider now move to 0? If so, I'd say the bug is fixed.

**Comment by blueplanet150** [comment]
Thank you :)
Yes it can move to zero.

**Comment by jackjt8** [comment]
Thank you for resolving that. I did notice it when I enabled logarithmic scaling however I couldn't quite figure it out.

**Review by jackjt8 — APPROVED** [review]
While I can't comment on how the code is laid out or anything like that; It seems to look good.

Important aspect is that not only does the slider function between 0.0, 0.01 -> 1.0 but text based inputs are still respected for values between 0.0 & 0.01. And values are correctly written to the JSON.

**Review by leMaik — APPROVED** [review]

**Comment by leMaik** [comment]
Thanks again, @blueplanet150. I just removed the commented console logger import.

**Pull request merged**
