### PR TITLE
Fix for tall flowers in materials tab

### PR DESCRIPTION
**Pull request by 073TheBoss**
Allows tall flowers (Rose bush, Lilac, & Peony) to be changed by the Materials Tab. This was caused by the `MinecraftBlockProviders.largeFlower()` function changing the name of the block before passing it on.

### CODE REVIEW

**Comment by aTom3333** [comment]
You may want to look at sunflowers and tall grass too i think

**Comment by 073TheBoss** [comment]
Both of those work correctly

**Comment by leMaik** [comment]
Can we change the `MinecraftBlockProviders.largeFlower()` to not append the "half" string to the block name instead? Because that's not actually it's block name (= block ID).

**Comment by 073TheBoss** [comment]
Changes have been made.

**Pull request merged**
