### PR TITLE
Add more labels to camera controls

### PR DESCRIPTION
**Pull request by ShirleyNekoDev**
- Have labels for each input field:
image
  Previous:
image

- Moved the "center camera" (above loaded chunks) button to the camera coordinate input.
- Also rewritten some of the tooltips and removed self-explanatory ones.

This PR is based on top of #1350

### CODE REVIEW

**Comment by NotStirred** [comment]
suggestion: (look at the `Position` (old), vs `Orientation` (new)
image

**Comment by ShirleyNekoDev** [comment]
done 👍 
image

**Review by NotStirred — CHANGES_REQUESTED** [review]
Looks like this suffers from something similar to what was fixed in #1205, the field isn't updated on focus loss

**Comment by ShirleyNekoDev** [comment]
> Looks like this suffers from something similar to what was fixed in #1205, the field change isn't applied on focus loss

This was not the case before, therefore I would prefer to fix that in a separate PR if needed.

**Comment by NotStirred** [comment]
Ah, I thought it was introduced by this PR. Yep we should do it in a different PR I'll make an issue now if there isn't one already

**Review by NotStirred — APPROVED** [review]

**Comment by NotStirred** [comment]
yep, it's https://github.com/chunky-dev/chunky/issues/712

**Pull request merged**
