### PR TITLE
Add render region mode.

### PR DESCRIPTION
**Pull request by ThatRedox**
Add settings to crop the camera frame (similar to lens shift).
image
These allow for the advanced user to easily render multiple parts of an image and recombine them later:
split (Medium)
sunset (Medium)

The `Width` and `Height` entries are the new "virtual" image width and height, of which Chunky will render a portion of. The width & height in the `Scene` tab along with the `Crop X Offset` and `Crop Y Offset` determine the exact portion of the full image to render.

### CODE REVIEW

**Comment by ThatRedox** [comment]
Note: Currently builds are failing due to an expired certificate.

**Comment by leMaik** [comment]
I wonder if we should switch _full width_ and _width_ (and height). The _width_ in the crop settings is now the "scene width", whereas the scene width is the width of the cropped part that is rendered… I find that a bit confusing. :thinking:

**Comment by ThatRedox** [comment]
New UI:
image
image

**Comment by leMaik** [comment]
Is the canvas size the virtual size now?

**Comment by ThatRedox** [comment]
Yes, the canvas size is now the virtual size.

**Pull request merged**
