### PR TITLE
New resource pack selection dialog and improved resource pack loading

### PR DESCRIPTION
**Pull request by ShirleyNekoDev**
image

### CODE REVIEW

**Comment by Peregrine05** [comment]
Please re-add loading resource packs from directories other than the Minecraft directory.

**Comment by ShirleyNekoDev** [comment]
@Peregrine05 added `browse for resource packs dialog` ("+" button) and replaced unicode glyphs with custom icons
image

**Comment by Peregrine05** [comment]
Thank you.

**Comment by leMaik** [comment]
The UI looks amazing! :clap: Just from looking at it, I have two questions though:

1. What does "Clear all" mean and what's the difference to "Deselect all"?
2. Should we change the "+" button and give it an explicit label? I first looked for a "Browse…" button or something like that.

**Comment by ShirleyNekoDev** [comment]
> 1. What does "Clear all" mean and what's the difference to "Deselect all"?

Select All = `Ctrl + A` (selection for packs as in "select these packs and use the arrows to move them between the columns")
Would "Remove All" or "Clear List" be a better name than "Clear All"?

> 2. Should we change the "+" button and give it an explicit label? I first looked for a "Browse…" button or something like that.

Would be an option, but I'm not sure if this change is necessary. Below the right list is enough space for it, if we want to have "Browse...".

**Comment by ShirleyNekoDev** [comment]
Removed selection buttons, added context menu, moved browse button (now with label):
image
(remind me later to add context menu to scene and world selection dialog too)

**Comment by ShirleyNekoDev** [comment]
Always has been :)

**Pull request merged**
